[
   {
      "QuestionID":"1",
      "AnswerID":"0",
      "Select":"1:100"
   },
   {
      "QuestionID":"2",
      "AnswerID":"0",
      "Text":["M","F"]
   },
   {
      "QuestionID":"3",
      "AnswerID":"0",
      "Text":"Arctic (Siberian or Eskimo)"
   },
   {
      "QuestionID":"3",
      "AnswerID":"1",
      "Text":"Caucasian (European)"
   },
   {
      "QuestionID":"3",
      "AnswerID":"2",
      "Text":"Caucasian (Indian)"
   },
   {
      "QuestionID":"3",
      "AnswerID":"3",
      "Text":"Caucasian (Middle East)"
   },
   {
      "QuestionID":"3",
      "AnswerID":"4",
      "Text":"Caucasian (North African or Other)"
   },
   {
      "QuestionID":"3",
      "AnswerID":"5",
      "Text":"Indigenous Australian"
   },
   {
      "QuestionID":"3",
      "AnswerID":"6",
      "Text":"Native American"
   },
   {
      "QuestionID":"3",
      "AnswerID":"7",
      "Text":"North East Asian (Mongol - Tibetan - Korean Japanese - etc)"
   },
   {
      "QuestionID":"3",
      "AnswerID":"8",
      "Text":"Pacific (Polynesian - Micronesian - etc)"
   },
   {
      "QuestionID":"3",
      "AnswerID":"9",
      "Text":"South East Asian (Chinese -  Thai - Malay - Filipino - etc)"
   },
   {
      "QuestionID":"3",
      "AnswerID":"10",
      "Text":"West African"
   },
   {
      "QuestionID":"3",
      "AnswerID":"11",
      "Text":"Bushmen"
   },
   {
      "QuestionID":"3",
      "AnswerID":"12",
      "Text":"Ethiopian"
   },
   {
      "QuestionID":"3",
      "AnswerID":"13",
      "Text":"Other Race"
   },
   {
      "QuestionID":"4",
      "AnswerID":"0",
      "Text":"Right"
   },
   {
      "QuestionID":"4",
      "AnswerID":"1",
      "Text":"Left"
   },
   {
      "QuestionID":"5",
      "AnswerID":"0",
      "Text":"Cochlear implant electric only"
   },
   {
      "QuestionID":"5",
      "AnswerID":"1",
      "Text":"Cochlear implant"
   },
   {
      "QuestionID":"5",
      "AnswerID":"2",
      "Text":"Electro acoustic"
   },
   {
      "QuestionID":"6",
      "AnswerID":"0",
      "Text":"Cochlear implant electric only"
   },
   {
      "QuestionID":"6",
      "AnswerID":"1",
      "Text":"Cochlear implant electro acoustic"
   },
   {
      "QuestionID":"6",
      "AnswerID":"2",
      "Text":"Hearing Aide"
   },
   {
      "QuestionID":"6",
      "AnswerID":"3",
      "Text":"Nothing"
   },
   {
      "QuestionID":"7",
      "AnswerID":"0",
      "Text":"10.0"
   },
   {
      "QuestionID":"7",
      "AnswerID":"1",
      "Text":"10.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"2",
      "Text":"10.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"3",
      "Text":"10.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"4",
      "Text":"10.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"5",
      "Text":"10.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"6",
      "Text":"10.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"7",
      "Text":"10.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"8",
      "Text":"10.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"9",
      "Text":"10.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"10",
      "Text":"11"
   },
   {
      "QuestionID":"7",
      "AnswerID":"11",
      "Text":"11.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"12",
      "Text":"11.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"13",
      "Text":"11.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"14",
      "Text":"11.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"15",
      "Text":"11.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"16",
      "Text":"11.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"17",
      "Text":"11.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"18",
      "Text":"11.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"19",
      "Text":"11.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"20",
      "Text":"12"
   },
   {
      "QuestionID":"7",
      "AnswerID":"21",
      "Text":"12.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"22",
      "Text":"12.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"23",
      "Text":"12.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"24",
      "Text":"12.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"25",
      "Text":"12.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"26",
      "Text":"12.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"27",
      "Text":"12.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"28",
      "Text":"12.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"29",
      "Text":"12.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"30",
      "Text":"13"
   },
   {
      "QuestionID":"7",
      "AnswerID":"31",
      "Text":"13.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"32",
      "Text":"13.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"33",
      "Text":"13.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"34",
      "Text":"13.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"35",
      "Text":"13.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"36",
      "Text":"13.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"37",
      "Text":"13.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"38",
      "Text":"13.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"39",
      "Text":"13.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"40",
      "Text":"14"
   },
   {
      "QuestionID":"7",
      "AnswerID":"41",
      "Text":"14.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"42",
      "Text":"14.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"43",
      "Text":"14.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"44",
      "Text":"14.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"45",
      "Text":"14.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"46",
      "Text":"14.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"47",
      "Text":"14.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"48",
      "Text":"14.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"49",
      "Text":"14.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"50",
      "Text":"15"
   },
   {
      "QuestionID":"7",
      "AnswerID":"51",
      "Text":"15.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"52",
      "Text":"15.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"53",
      "Text":"15.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"54",
      "Text":"15.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"55",
      "Text":"15.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"56",
      "Text":"15.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"57",
      "Text":"15.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"58",
      "Text":"15.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"59",
      "Text":"15.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"60",
      "Text":"16"
   },
   {
      "QuestionID":"7",
      "AnswerID":"61",
      "Text":"16.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"62",
      "Text":"16.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"63",
      "Text":"16.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"64",
      "Text":"16.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"65",
      "Text":"16.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"66",
      "Text":"16.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"67",
      "Text":"16.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"68",
      "Text":"16.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"69",
      "Text":"16.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"70",
      "Text":"17"
   },
   {
      "QuestionID":"7",
      "AnswerID":"71",
      "Text":"17.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"72",
      "Text":"17.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"73",
      "Text":"17.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"74",
      "Text":"17.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"75",
      "Text":"17.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"76",
      "Text":"17.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"77",
      "Text":"17.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"78",
      "Text":"17.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"79",
      "Text":"17.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"80",
      "Text":"18"
   },
   {
      "QuestionID":"7",
      "AnswerID":"81",
      "Text":"18.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"82",
      "Text":"18.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"83",
      "Text":"18.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"84",
      "Text":"18.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"85",
      "Text":"18.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"86",
      "Text":"18.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"87",
      "Text":"18.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"88",
      "Text":"18.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"89",
      "Text":"18.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"90",
      "Text":"19"
   },
   {
      "QuestionID":"7",
      "AnswerID":"91",
      "Text":"19.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"92",
      "Text":"19.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"93",
      "Text":"19.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"94",
      "Text":"19.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"95",
      "Text":"19.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"96",
      "Text":"19.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"97",
      "Text":"19.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"98",
      "Text":"19.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"99",
      "Text":"19.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"100",
      "Text":"20"
   },
   {
      "QuestionID":"7",
      "AnswerID":"101",
      "Text":"20.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"102",
      "Text":"20.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"103",
      "Text":"20.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"104",
      "Text":"20.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"105",
      "Text":"20.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"106",
      "Text":"20.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"107",
      "Text":"20.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"108",
      "Text":"20.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"109",
      "Text":"20.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"110",
      "Text":"21"
   },
   {
      "QuestionID":"7",
      "AnswerID":"111",
      "Text":"21.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"112",
      "Text":"21.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"113",
      "Text":"21.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"114",
      "Text":"21.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"115",
      "Text":"21.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"116",
      "Text":"21.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"117",
      "Text":"21.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"118",
      "Text":"21.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"119",
      "Text":"21.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"120",
      "Text":"22"
   },
   {
      "QuestionID":"7",
      "AnswerID":"121",
      "Text":"22.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"122",
      "Text":"22.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"123",
      "Text":"22.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"124",
      "Text":"22.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"125",
      "Text":"22.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"126",
      "Text":"22.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"127",
      "Text":"22.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"128",
      "Text":"22.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"129",
      "Text":"22.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"130",
      "Text":"23"
   },
   {
      "QuestionID":"7",
      "AnswerID":"131",
      "Text":"23.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"132",
      "Text":"23.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"133",
      "Text":"23.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"134",
      "Text":"23.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"135",
      "Text":"23.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"136",
      "Text":"23.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"137",
      "Text":"23.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"138",
      "Text":"23.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"139",
      "Text":"23.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"140",
      "Text":"24"
   },
   {
      "QuestionID":"7",
      "AnswerID":"141",
      "Text":"24.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"142",
      "Text":"24.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"143",
      "Text":"24.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"144",
      "Text":"24.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"145",
      "Text":"24.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"146",
      "Text":"24.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"147",
      "Text":"24.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"148",
      "Text":"24.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"149",
      "Text":"24.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"150",
      "Text":"25"
   },
   {
      "QuestionID":"7",
      "AnswerID":"151",
      "Text":"25.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"152",
      "Text":"25.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"153",
      "Text":"25.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"154",
      "Text":"25.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"155",
      "Text":"25.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"156",
      "Text":"25.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"157",
      "Text":"25.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"158",
      "Text":"25.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"159",
      "Text":"25.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"160",
      "Text":"26"
   },
   {
      "QuestionID":"7",
      "AnswerID":"161",
      "Text":"26.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"162",
      "Text":"26.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"163",
      "Text":"26.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"164",
      "Text":"26.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"165",
      "Text":"26.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"166",
      "Text":"26.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"167",
      "Text":"26.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"168",
      "Text":"26.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"169",
      "Text":"26.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"170",
      "Text":"27"
   },
   {
      "QuestionID":"7",
      "AnswerID":"171",
      "Text":"27.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"172",
      "Text":"27.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"173",
      "Text":"27.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"174",
      "Text":"27.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"175",
      "Text":"27.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"176",
      "Text":"27.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"177",
      "Text":"27.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"178",
      "Text":"27.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"179",
      "Text":"27.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"180",
      "Text":"28"
   },
   {
      "QuestionID":"7",
      "AnswerID":"181",
      "Text":"28.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"182",
      "Text":"28.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"183",
      "Text":"28.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"184",
      "Text":"28.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"185",
      "Text":"28.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"186",
      "Text":"28.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"187",
      "Text":"28.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"188",
      "Text":"28.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"189",
      "Text":"28.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"190",
      "Text":"29"
   },
   {
      "QuestionID":"7",
      "AnswerID":"191",
      "Text":"29.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"192",
      "Text":"29.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"193",
      "Text":"29.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"194",
      "Text":"29.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"195",
      "Text":"29.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"196",
      "Text":"29.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"197",
      "Text":"29.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"198",
      "Text":"29.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"199",
      "Text":"29.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"200",
      "Text":"30"
   },
   {
      "QuestionID":"7",
      "AnswerID":"201",
      "Text":"30.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"202",
      "Text":"30.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"203",
      "Text":"30.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"204",
      "Text":"30.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"205",
      "Text":"30.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"206",
      "Text":"30.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"207",
      "Text":"30.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"208",
      "Text":"30.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"209",
      "Text":"30.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"210",
      "Text":"31"
   },
   {
      "QuestionID":"7",
      "AnswerID":"211",
      "Text":"31.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"212",
      "Text":"31.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"213",
      "Text":"31.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"214",
      "Text":"31.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"215",
      "Text":"31.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"216",
      "Text":"31.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"217",
      "Text":"31.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"218",
      "Text":"31.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"219",
      "Text":"31.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"220",
      "Text":"32"
   },
   {
      "QuestionID":"7",
      "AnswerID":"221",
      "Text":"32.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"222",
      "Text":"32.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"223",
      "Text":"32.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"224",
      "Text":"32.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"225",
      "Text":"32.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"226",
      "Text":"32.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"227",
      "Text":"32.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"228",
      "Text":"32.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"229",
      "Text":"32.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"230",
      "Text":"33"
   },
   {
      "QuestionID":"7",
      "AnswerID":"231",
      "Text":"33.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"232",
      "Text":"33.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"233",
      "Text":"33.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"234",
      "Text":"33.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"235",
      "Text":"33.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"236",
      "Text":"33.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"237",
      "Text":"33.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"238",
      "Text":"33.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"239",
      "Text":"33.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"240",
      "Text":"34"
   },
   {
      "QuestionID":"7",
      "AnswerID":"241",
      "Text":"34.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"242",
      "Text":"34.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"243",
      "Text":"34.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"244",
      "Text":"34.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"245",
      "Text":"34.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"246",
      "Text":"34.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"247",
      "Text":"34.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"248",
      "Text":"34.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"249",
      "Text":"34.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"250",
      "Text":"35"
   },
   {
      "QuestionID":"7",
      "AnswerID":"251",
      "Text":"35.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"252",
      "Text":"35.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"253",
      "Text":"35.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"254",
      "Text":"35.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"255",
      "Text":"35.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"256",
      "Text":"35.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"257",
      "Text":"35.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"258",
      "Text":"35.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"259",
      "Text":"35.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"260",
      "Text":"36"
   },
   {
      "QuestionID":"7",
      "AnswerID":"261",
      "Text":"36.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"262",
      "Text":"36.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"263",
      "Text":"36.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"264",
      "Text":"36.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"265",
      "Text":"36.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"266",
      "Text":"36.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"267",
      "Text":"36.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"268",
      "Text":"36.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"269",
      "Text":"36.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"270",
      "Text":"37"
   },
   {
      "QuestionID":"7",
      "AnswerID":"271",
      "Text":"37.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"272",
      "Text":"37.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"273",
      "Text":"37.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"274",
      "Text":"37.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"275",
      "Text":"37.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"276",
      "Text":"37.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"277",
      "Text":"37.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"278",
      "Text":"37.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"279",
      "Text":"37.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"280",
      "Text":"38"
   },
   {
      "QuestionID":"7",
      "AnswerID":"281",
      "Text":"38.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"282",
      "Text":"38.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"283",
      "Text":"38.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"284",
      "Text":"38.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"285",
      "Text":"38.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"286",
      "Text":"38.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"287",
      "Text":"38.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"288",
      "Text":"38.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"289",
      "Text":"38.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"290",
      "Text":"39"
   },
   {
      "QuestionID":"7",
      "AnswerID":"291",
      "Text":"39.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"292",
      "Text":"39.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"293",
      "Text":"39.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"294",
      "Text":"39.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"295",
      "Text":"39.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"296",
      "Text":"39.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"297",
      "Text":"39.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"298",
      "Text":"39.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"299",
      "Text":"39.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"300",
      "Text":"40"
   },
   {
      "QuestionID":"7",
      "AnswerID":"301",
      "Text":"40.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"302",
      "Text":"40.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"303",
      "Text":"40.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"304",
      "Text":"40.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"305",
      "Text":"40.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"306",
      "Text":"40.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"307",
      "Text":"40.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"308",
      "Text":"40.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"309",
      "Text":"40.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"310",
      "Text":"41"
   },
   {
      "QuestionID":"7",
      "AnswerID":"311",
      "Text":"41.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"312",
      "Text":"41.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"313",
      "Text":"41.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"314",
      "Text":"41.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"315",
      "Text":"41.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"316",
      "Text":"41.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"317",
      "Text":"41.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"318",
      "Text":"41.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"319",
      "Text":"41.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"320",
      "Text":"42"
   },
   {
      "QuestionID":"7",
      "AnswerID":"321",
      "Text":"42.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"322",
      "Text":"42.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"323",
      "Text":"42.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"324",
      "Text":"42.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"325",
      "Text":"42.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"326",
      "Text":"42.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"327",
      "Text":"42.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"328",
      "Text":"42.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"329",
      "Text":"42.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"330",
      "Text":"43"
   },
   {
      "QuestionID":"7",
      "AnswerID":"331",
      "Text":"43.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"332",
      "Text":"43.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"333",
      "Text":"43.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"334",
      "Text":"43.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"335",
      "Text":"43.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"336",
      "Text":"43.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"337",
      "Text":"43.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"338",
      "Text":"43.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"339",
      "Text":"43.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"340",
      "Text":"44"
   },
   {
      "QuestionID":"7",
      "AnswerID":"341",
      "Text":"44.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"342",
      "Text":"44.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"343",
      "Text":"44.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"344",
      "Text":"44.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"345",
      "Text":"44.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"346",
      "Text":"44.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"347",
      "Text":"44.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"348",
      "Text":"44.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"349",
      "Text":"44.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"350",
      "Text":"45"
   },
   {
      "QuestionID":"7",
      "AnswerID":"351",
      "Text":"45.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"352",
      "Text":"45.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"353",
      "Text":"45.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"354",
      "Text":"45.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"355",
      "Text":"45.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"356",
      "Text":"45.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"357",
      "Text":"45.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"358",
      "Text":"45.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"359",
      "Text":"45.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"360",
      "Text":"46"
   },
   {
      "QuestionID":"7",
      "AnswerID":"361",
      "Text":"46.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"362",
      "Text":"46.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"363",
      "Text":"46.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"364",
      "Text":"46.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"365",
      "Text":"46.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"366",
      "Text":"46.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"367",
      "Text":"46.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"368",
      "Text":"46.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"369",
      "Text":"46.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"370",
      "Text":"47"
   },
   {
      "QuestionID":"7",
      "AnswerID":"371",
      "Text":"47.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"372",
      "Text":"47.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"373",
      "Text":"47.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"374",
      "Text":"47.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"375",
      "Text":"47.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"376",
      "Text":"47.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"377",
      "Text":"47.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"378",
      "Text":"47.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"379",
      "Text":"47.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"380",
      "Text":"48"
   },
   {
      "QuestionID":"7",
      "AnswerID":"381",
      "Text":"48.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"382",
      "Text":"48.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"383",
      "Text":"48.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"384",
      "Text":"48.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"385",
      "Text":"48.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"386",
      "Text":"48.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"387",
      "Text":"48.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"388",
      "Text":"48.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"389",
      "Text":"48.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"390",
      "Text":"49"
   },
   {
      "QuestionID":"7",
      "AnswerID":"391",
      "Text":"49.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"392",
      "Text":"49.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"393",
      "Text":"49.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"394",
      "Text":"49.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"395",
      "Text":"49.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"396",
      "Text":"49.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"397",
      "Text":"49.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"398",
      "Text":"49.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"399",
      "Text":"49.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"400",
      "Text":"50"
   },
   {
      "QuestionID":"7",
      "AnswerID":"401",
      "Text":"50.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"402",
      "Text":"50.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"403",
      "Text":"50.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"404",
      "Text":"50.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"405",
      "Text":"50.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"406",
      "Text":"50.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"407",
      "Text":"50.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"408",
      "Text":"50.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"409",
      "Text":"50.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"410",
      "Text":"51"
   },
   {
      "QuestionID":"7",
      "AnswerID":"411",
      "Text":"51.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"412",
      "Text":"51.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"413",
      "Text":"51.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"414",
      "Text":"51.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"415",
      "Text":"51.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"416",
      "Text":"51.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"417",
      "Text":"51.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"418",
      "Text":"51.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"419",
      "Text":"51.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"420",
      "Text":"52"
   },
   {
      "QuestionID":"7",
      "AnswerID":"421",
      "Text":"52.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"422",
      "Text":"52.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"423",
      "Text":"52.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"424",
      "Text":"52.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"425",
      "Text":"52.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"426",
      "Text":"52.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"427",
      "Text":"52.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"428",
      "Text":"52.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"429",
      "Text":"52.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"430",
      "Text":"53"
   },
   {
      "QuestionID":"7",
      "AnswerID":"431",
      "Text":"53.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"432",
      "Text":"53.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"433",
      "Text":"53.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"434",
      "Text":"53.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"435",
      "Text":"53.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"436",
      "Text":"53.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"437",
      "Text":"53.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"438",
      "Text":"53.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"439",
      "Text":"53.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"440",
      "Text":"54"
   },
   {
      "QuestionID":"7",
      "AnswerID":"441",
      "Text":"54.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"442",
      "Text":"54.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"443",
      "Text":"54.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"444",
      "Text":"54.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"445",
      "Text":"54.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"446",
      "Text":"54.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"447",
      "Text":"54.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"448",
      "Text":"54.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"449",
      "Text":"54.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"450",
      "Text":"55"
   },
   {
      "QuestionID":"7",
      "AnswerID":"451",
      "Text":"55.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"452",
      "Text":"55.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"453",
      "Text":"55.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"454",
      "Text":"55.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"455",
      "Text":"55.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"456",
      "Text":"55.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"457",
      "Text":"55.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"458",
      "Text":"55.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"459",
      "Text":"55.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"460",
      "Text":"56"
   },
   {
      "QuestionID":"7",
      "AnswerID":"461",
      "Text":"56.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"462",
      "Text":"56.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"463",
      "Text":"56.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"464",
      "Text":"56.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"465",
      "Text":"56.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"466",
      "Text":"56.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"467",
      "Text":"56.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"468",
      "Text":"56.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"469",
      "Text":"56.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"470",
      "Text":"57"
   },
   {
      "QuestionID":"7",
      "AnswerID":"471",
      "Text":"57.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"472",
      "Text":"57.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"473",
      "Text":"57.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"474",
      "Text":"57.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"475",
      "Text":"57.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"476",
      "Text":"57.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"477",
      "Text":"57.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"478",
      "Text":"57.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"479",
      "Text":"57.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"480",
      "Text":"58"
   },
   {
      "QuestionID":"7",
      "AnswerID":"481",
      "Text":"58.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"482",
      "Text":"58.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"483",
      "Text":"58.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"484",
      "Text":"58.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"485",
      "Text":"58.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"486",
      "Text":"58.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"487",
      "Text":"58.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"488",
      "Text":"58.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"489",
      "Text":"58.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"490",
      "Text":"59"
   },
   {
      "QuestionID":"7",
      "AnswerID":"491",
      "Text":"59.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"492",
      "Text":"59.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"493",
      "Text":"59.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"494",
      "Text":"59.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"495",
      "Text":"59.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"496",
      "Text":"59.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"497",
      "Text":"59.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"498",
      "Text":"59.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"499",
      "Text":"59.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"500",
      "Text":"60"
   },
   {
      "QuestionID":"7",
      "AnswerID":"501",
      "Text":"60.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"502",
      "Text":"60.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"503",
      "Text":"60.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"504",
      "Text":"60.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"505",
      "Text":"60.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"506",
      "Text":"60.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"507",
      "Text":"60.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"508",
      "Text":"60.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"509",
      "Text":"60.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"510",
      "Text":"61"
   },
   {
      "QuestionID":"7",
      "AnswerID":"511",
      "Text":"61.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"512",
      "Text":"61.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"513",
      "Text":"61.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"514",
      "Text":"61.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"515",
      "Text":"61.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"516",
      "Text":"61.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"517",
      "Text":"61.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"518",
      "Text":"61.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"519",
      "Text":"61.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"520",
      "Text":"62"
   },
   {
      "QuestionID":"7",
      "AnswerID":"521",
      "Text":"62.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"522",
      "Text":"62.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"523",
      "Text":"62.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"524",
      "Text":"62.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"525",
      "Text":"62.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"526",
      "Text":"62.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"527",
      "Text":"62.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"528",
      "Text":"62.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"529",
      "Text":"62.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"530",
      "Text":"63"
   },
   {
      "QuestionID":"7",
      "AnswerID":"531",
      "Text":"63.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"532",
      "Text":"63.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"533",
      "Text":"63.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"534",
      "Text":"63.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"535",
      "Text":"63.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"536",
      "Text":"63.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"537",
      "Text":"63.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"538",
      "Text":"63.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"539",
      "Text":"63.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"540",
      "Text":"64"
   },
   {
      "QuestionID":"7",
      "AnswerID":"541",
      "Text":"64.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"542",
      "Text":"64.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"543",
      "Text":"64.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"544",
      "Text":"64.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"545",
      "Text":"64.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"546",
      "Text":"64.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"547",
      "Text":"64.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"548",
      "Text":"64.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"549",
      "Text":"64.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"550",
      "Text":"65"
   },
   {
      "QuestionID":"7",
      "AnswerID":"551",
      "Text":"65.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"552",
      "Text":"65.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"553",
      "Text":"65.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"554",
      "Text":"65.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"555",
      "Text":"65.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"556",
      "Text":"65.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"557",
      "Text":"65.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"558",
      "Text":"65.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"559",
      "Text":"65.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"560",
      "Text":"66"
   },
   {
      "QuestionID":"7",
      "AnswerID":"561",
      "Text":"66.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"562",
      "Text":"66.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"563",
      "Text":"66.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"564",
      "Text":"66.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"565",
      "Text":"66.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"566",
      "Text":"66.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"567",
      "Text":"66.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"568",
      "Text":"66.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"569",
      "Text":"66.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"570",
      "Text":"67"
   },
   {
      "QuestionID":"7",
      "AnswerID":"571",
      "Text":"67.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"572",
      "Text":"67.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"573",
      "Text":"67.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"574",
      "Text":"67.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"575",
      "Text":"67.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"576",
      "Text":"67.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"577",
      "Text":"67.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"578",
      "Text":"67.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"579",
      "Text":"67.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"580",
      "Text":"68"
   },
   {
      "QuestionID":"7",
      "AnswerID":"581",
      "Text":"68.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"582",
      "Text":"68.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"583",
      "Text":"68.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"584",
      "Text":"68.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"585",
      "Text":"68.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"586",
      "Text":"68.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"587",
      "Text":"68.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"588",
      "Text":"68.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"589",
      "Text":"68.9"
   },
   {
      "QuestionID":"7",
      "AnswerID":"590",
      "Text":"69"
   },
   {
      "QuestionID":"7",
      "AnswerID":"591",
      "Text":"69.1"
   },
   {
      "QuestionID":"7",
      "AnswerID":"592",
      "Text":"69.2"
   },
   {
      "QuestionID":"7",
      "AnswerID":"593",
      "Text":"69.3"
   },
   {
      "QuestionID":"7",
      "AnswerID":"594",
      "Text":"69.4"
   },
   {
      "QuestionID":"7",
      "AnswerID":"595",
      "Text":"69.5"
   },
   {
      "QuestionID":"7",
      "AnswerID":"596",
      "Text":"69.6"
   },
   {
      "QuestionID":"7",
      "AnswerID":"597",
      "Text":"69.7"
   },
   {
      "QuestionID":"7",
      "AnswerID":"598",
      "Text":"69.8"
   },
   {
      "QuestionID":"7",
      "AnswerID":"599",
      "Text":"69.9"
   },
   {
      "QuestionID":"8",
      "AnswerID":"0",
      "Text":"Congenital"
   },
   {
      "QuestionID":"8",
      "AnswerID":"1",
      "Text":"Progressive"
   },
   {
      "QuestionID":"8",
      "AnswerID":"2",
      "Text":"Trauma"
   },
   {
      "QuestionID":"8",
      "AnswerID":"3",
      "Text":"Infection"
   },
   {
      "QuestionID":"8",
      "AnswerID":"4",
      "Text":"Ototoxicity"
   },
   {
      "QuestionID":"8",
      "AnswerID":"5",
      "Text":"Meningitis"
   },
   {
      "QuestionID":"8",
      "AnswerID":"6",
      "Text":"Menier's Disease"
   },
   {
      "QuestionID":"8",
      "AnswerID":"7",
      "Text":"Other"
   },
   {
      "QuestionID":"10",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"10",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"11",
      "AnswerID":"0",
      "Text":"Right"
   },
   {
      "QuestionID":"11",
      "AnswerID":"1",
      "Text":"Left"
   },
   {
      "QuestionID":"11",
      "AnswerID":"2",
      "Text":"Both"
   },
   {
      "QuestionID":"12",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"12",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"13",
      "AnswerID":"0",
      "Text":"Right"
   },
   {
      "QuestionID":"13",
      "AnswerID":"1",
      "Text":"Left"
   },
   {
      "QuestionID":"13",
      "AnswerID":"2",
      "Text":"Both"
   },
   {
      "QuestionID":"15",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"15",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"16",
      "AnswerID":"0",
      "Text":"Right"
   },
   {
      "QuestionID":"16",
      "AnswerID":"1",
      "Text":"Left"
   },
   {
      "QuestionID":"16",
      "AnswerID":"2",
      "Text":"Neither"
   },
   {
      "QuestionID":"17",
      "AnswerID":"0",
      "Text":"Normal"
   },
   {
      "QuestionID":"17",
      "AnswerID":"1",
      "Text":"Fluid"
   },
   {
      "QuestionID":"17",
      "AnswerID":"2",
      "Text":"Mass"
   },
   {
      "QuestionID":"17",
      "AnswerID":"3",
      "Text":"Cholesteatoma"
   },
   {
      "QuestionID":"17",
      "AnswerID":"4",
      "Text":"Retracted"
   },
   {
      "QuestionID":"17",
      "AnswerID":"5",
      "Text":"Perforation"
   },
   {
      "QuestionID":"17",
      "AnswerID":"6",
      "Text":"Other"
   },
   {
      "QuestionID":"18",
      "AnswerID":"0",
      "Text":"Normal"
   },
   {
      "QuestionID":"18",
      "AnswerID":"1",
      "Text":"Fluid"
   },
   {
      "QuestionID":"18",
      "AnswerID":"2",
      "Text":"Mass"
   },
   {
      "QuestionID":"18",
      "AnswerID":"3",
      "Text":"Cholesteatoma"
   },
   {
      "QuestionID":"18",
      "AnswerID":"4",
      "Text":"Retracted"
   },
   {
      "QuestionID":"18",
      "AnswerID":"5",
      "Text":"Perforation"
   },
   {
      "QuestionID":"18",
      "AnswerID":"6",
      "Text":"Other"
   },
   {
      "QuestionID":"19",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"19",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"21",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"21",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"22",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"22",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"23",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"23",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"24",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"24",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"24",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"25",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"25",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"25",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"26",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"26",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"26",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"27",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"27",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"27",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"28",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"28",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"28",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"29",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"29",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"30",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"30",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"30",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"31",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"31",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"31",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"32",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"32",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"32",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"33",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"33",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"34",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"34",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"34",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"35",
      "AnswerID":"0",
      "Text":"Right"
   },
   {
      "QuestionID":"35",
      "AnswerID":"1",
      "Text":"Left"
   },
   {
      "QuestionID":"35",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"36",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"36",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"36",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"37",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"37",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"37",
      "AnswerID":"2",
      "Text":"N\/A"
   },
   {
      "QuestionID":"39",
      "AnswerID":"0",
      "Text":"Right"
   },
   {
      "QuestionID":"39",
      "AnswerID":"1",
      "Text":"Left"
   },
   {
      "QuestionID":"41",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"41",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"42",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"42",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"44",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"44",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"45",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"45",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"46",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"46",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"47",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"47",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"49",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"49",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"50",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"50",
      "AnswerID":"1",
      "Text":"No"
   },
   {
      "QuestionID":"51",
      "AnswerID":"0",
      "Text":"Yes"
   },
   {
      "QuestionID":"51",
      "AnswerID":"1",
      "Text":"No"
   }
]